### PR TITLE
Initial commit of potential XML file

### PR DESCRIPTION
**Pull request by ChrisTruncer**
Hey guys,

A tool I have been working on (EyeWitness) is supposed to be able to identify default creds based off of a web site's "signature" (assuming there are default creds).  I was originally working on creating my own parseable file/database, and Rob mentioned that PwnWiki already has some of this information, and that it may be mutually beneficial to work on this together.  I agree.  I've tried to create an XML file containing the info you guys have already accumulated, and then added in an attribute for signatures which EyeWitness would look for.  I wanted to see if this looks ok to you guys, or if you think it somehow needs to be changed.

Thanks for any feedback, and hope to get a pretty big database going with you guys.

### CODE REVIEW

**Comment by mubix** [comment]
Most of the unsorted data is in a table in the readme.md if you want to take a swing at converting it all, there is a lot in there.

This isn't a hinderence on merging this pull request though just informational.

**Comment by ChrisTruncer** [comment]
Yeah, I did see all of them in the readme.  I largely didn't include them quite yet because I wanted to make sure this format was ok, or get feedback from you guys and modify the format, before having to do that across all the records.  Once everything has been signed off on, then the rest of the records can get added in.

**Comment by mubix** [comment]
Is the "SIGNATURE" a string that should show up in source? is that in the main page or in some other page?

**Comment by ChrisTruncer** [comment]
My take on it, for implementation into Eyewitness, is yes, it is a string,
or multiple strings, within the source code of the web application.  For
this to work, it would have to be a signature from the source code of the
default "splash" page of a web app. So for example, a wordpress site would
have a signature from the main website, not the /wp-admin directory, since
the main site is what would be initially discovered by a scanner, or a user
browsing the network.

On Apr 22, 2014, at 9:40 PM, Rob Fuller notifications@github.com wrote:

Is the "SIGNATURE" a string that should show up in source? is that in the
main page or in some other page?

## 

Reply to this email directly or view it on
GitHubhttps://github.com/pwnwiki/webappdefaultsdb/pull/2#issuecomment-41116180
.

**Comment by mubix** [comment]
@ChrisTruncer Haven't forgotten about this stuff. Any reason you closed it?

**Pull request closed without merging**
